[dynamic_color] Add tone-based colors to color scheme
material-foundation/flutter-packages pull request #599
Opened 2024-07-07 22:39 UTC by hasali19

## Description

Adds the new tone-based colors from Flutter 3.22 to the color scheme.

On API >= 34, the color values are retrieved directly from the Android OS.

On API >= 31, the existing core palette will continue to be used, with the mappings taken from https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md.

## Issues
Fixes #574 

## Checklist

- [x] I've reviewed the [contribution guide](https://github.com/material-foundation/flutter-packages/blob/main/CONTRIBUTING.md).
- [x] I've updated the package `CHANGELOG.md`

2024-07-09 14:53 UTC, Henry-Hiles commented
I'm trying to use this, but I get this error: `When a TonalPalette is created with fromList, tone must be one of [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 99, 100]`

2024-07-09 15:07 UTC, hasali19 commented
Interesting...I don't think I've changed anything related to that. Does the latest main branch work fine for you?

2024-07-09 16:37 UTC, Henry-Hiles commented
> Interesting...I don't think I've changed anything related to that. Does the latest main branch work fine for you?

Well, from pub it doesn't have the correct colours, but no errors. I switched the pubspec to use this fork, and boom: error. I'll try main asap.

2024-07-09 17:02 UTC, Henry-Hiles commented
I'm using DynamicColorBuilder ofc.

2024-07-09 17:18 UTC, hasali19 commented
Which flutter version are you using?

2024-07-09 17:21 UTC, Henry-Hiles commented
```
quadradical@quadraticpc ~/D/C/qlib (master)> flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision nixpkgs000 () • 1970-01-01 00:00:00
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

2024-07-09 17:32 UTC, hasali19 commented
Ok, I think I see the problem. Support for arbitrary colour tones were added in material_color_utilities 0.11.0, but stable flutter depends on 0.8.0. I just realised I was using the beta channel, which is why I didn't run into it.

I think the solution will be to sidestep material_color_utilities and try to get the colours from the native side for the API < 34 case as well.

2024-07-09 17:33 UTC, Henry-Hiles commented
Oh, I see, thanks!

2024-07-09 22:45 UTC, hasali19 commented
I've taken a different approach of implementing logic to "guess" tones that are missing from the common tones list, based on the implementation in material_color_utilities. This will be needed until flutter supports the new version.

@Henry-Hiles Can you confirm if this works for you now?

2024-07-09 22:49 UTC, Henry-Hiles commented
Sure, I'll test right now!

2024-07-09 22:52 UTC, Henry-Hiles commented
While this no longer has an error, it still has the same issues as without this PR (very similar colors so nothing looks correct)

2024-07-09 22:52 UTC, Henry-Hiles commented
![Screenshot_20240709-185210_QJobProcessor](https://github.com/material-foundation/flutter-packages/assets/71790868/4991cd4e-7099-4702-9a9d-3543afa1bb33)

2024-07-09 22:53 UTC, Henry-Hiles commented
As you can see, the navbar and background are the same, which isn't normal.

2024-07-09 23:09 UTC, hasali19 commented
I can't seem to reproduce that. Do you have an example repo/code you can share?

![Screenshot_1720566342](https://github.com/material-foundation/flutter-packages/assets/10169241/bfc0f669-5329-4412-a58c-9e01282feafe)

2024-07-09 23:11 UTC, Henry-Hiles commented
> I can't seem to reproduce that. Do you have an example repo/code you can share?
> 
> ![Screenshot_1720566342](https://private-user-images.githubusercontent.com/10169241/347173352-bfc0f669-5329-4412-a58c-9e01282feafe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjY5NzEsIm5iZiI6MTcyMDU2NjY3MSwicGF0aCI6Ii8xMDE2OTI0MS8zNDcxNzMzNTItYmZjMGY2NjktNTMyOS00NDEyLWE1OGMtOWUwMTI4MmZlYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMjIzODMzM2Y1NzlkYmQxMzYyNzI1Y2ZkNDY0NzNmYmUzYTc0ODMwYWQzZWZlOGFiZDBjNDYwNWE1NWUzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAB-YZ_g3Eg_pDAZMiDqZE3xvbwsLGykSGLrcD1tPWs)

Hmm it happened when I upgraded to 3.22.2, I'll see if I can make a test repo.

2024-07-10 18:18 UTC, Henry-Hiles approved these changes

2024-07-14 02:53 UTC, resucutie commented
After building my application using it, the primary color isn't accurate
![image](https://github.com/user-attachments/assets/aac53eab-12c6-4a72-8f9a-a54ac86ed061)
![image](https://github.com/user-attachments/assets/7973d752-5b9e-46fe-bfb2-4d1d7db641e8)

2024-07-14 05:47 UTC, hasali19 commented
Which android version are you using?

2024-07-14 14:42 UTC, resucutie commented
Android 14

2024-07-14 15:25 UTC, hasali19 commented
On Android 14, this should be using the primary colour that is provided directly by the system.

Could you share your flutter version, debug logs and a sample project if possible.

2024-07-14 17:42 UTC, JunioJsv commented
There's something wrong with the implementation. I just tested it in my project, and the colors don't match those of the system, which is predominantly green. However, in the app, the predominant color is dark blue. I'm using Android 14 and Flutter 3.22.0.

![WhatsApp Image 2024-07-14 at 14 37 24](https://github.com/user-attachments/assets/9b421a63-e206-4c50-ab62-83387c2bc833)
![WhatsApp Image 2024-07-14 at 14 37 23](https://github.com/user-attachments/assets/1a204442-a228-40f8-9b86-88c4d938a814)

2024-07-14 17:45 UTC, JunioJsv commented
Here's the link to the project where I ran the test: https://github.com/JunioJsv/minimum-flutter

![image](https://github.com/user-attachments/assets/de2ff6b2-0385-4bd0-b5fa-74dc3da1fd6b)

2024-07-14 20:30 UTC, hasali19 commented
I'm not able to reproduce the issue on my device.

Could you share the debug logs when you run the app. In particular, do you see a line similar to:

```
I/flutter (18079): dynamic_color: Color scheme detected.
```

2024-07-15 11:25 UTC, hasali19 commented
It seems this may be a common issue on Samsung devices, affecting the official Android material library as well - https://github.com/material-components/material-components-android/issues/3924. Samsung reports incorrect values for the new colours added in Android 14.

Do you see dynamic colours working correctly in other apps, e.g. Google apps?

Given this is a Samsung specific issue, not really sure what we can do here.

2024-07-15 11:41 UTC, JunioJsv commented
> It seems this may be a common issue on Samsung devices, affecting the official Android material library as well - [material-components/material-components-android#3924](https://github.com/material-components/material-components-android/issues/3924). Samsung reports incorrect values for the new colours added in Android 14.
> 
> Do you see dynamic colours working correctly in other apps, e.g. Google apps?
> 
> Given this is a Samsung specific issue, not really sure what we can do here.

Indeed, the Google apps are also displaying the wrong tone, dark blue, and my device is a Samsung A54.

2024-07-21 18:53 UTC, resucutie commented
I've decided to finally publish a "just build it" branch of my project: https://github.com/resucutie/localbooru/tree/dynamic-colors-pr-fix-test

@hasali19 feel free to build and test it

2024-07-21 18:58 UTC, hasali19 commented
@resucutie Thanks, I'll take a look.

Could you also share your flutter version please?

2024-07-21 21:52 UTC, hasali19 commented
From what I can see this is working as expected; Android's quick settings tiles use a slightly different shade of the primary colour.

You can see [here](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/packages/SystemUI/res/values/styles.xml;l=432) that the `shadeActive` colour (used by the Android system for the quick settings tiles) uses tone 90 of the primary colour, while the [material library](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md) defines primary in the colour scheme as tone 40 in light mode and 80 in dark mode.

2024-07-21 22:07 UTC, resucutie commented
Welp, what about in comparasion to other apps? It looks odd, or I guess it is the consensus here, like if it is using the wrong color shade, but I am not sure

2024-07-21 22:13 UTC, hasali19 commented
Do you mean you are seeing different colours compared to other apps using the same dynamic colour scheme?

This implementation should be using the same colours as those used by the official native material library. If this is not the case, please share a repro.

2024-07-30 20:12 UTC, resucutie commented
I've (finally) tested it and apparently it indeed take the correct colors. It is a bit odd that it looks different on an emulator
![Screenshot_20240730-170947_LocalBooru.png](https://github.com/user-attachments/assets/b576b374-1f31-433b-bf40-7873a3226d3d)

![Screenshot_20240730-170950_Settings.png](https://github.com/user-attachments/assets/0609290a-4831-4922-b483-f98971106525)

PR is good I think

2024-08-09 05:13 UTC, wildsylvan commented
in our case, after activating dynamic colors:
![image](https://github.com/user-attachments/assets/00d975bb-fbc6-4ec4-9fef-684180faee7f)
primary container e secondary container became the same color!

---

look at the cards (list a/b and the new list fab. they should be different colors but with dynamic colors they become the same)

### without dynamic colors (correct)
![Screenshot_2024-08-09-07-07-49-47_304e098f875053d2a3a592b681756698](https://github.com/user-attachments/assets/59719e50-61ab-4660-b92e-08301bf29ccb)

### with dynamic colors (wrong)
![Screenshot_2024-08-09-07-07-28-30_304e098f875053d2a3a592b681756698](https://github.com/user-attachments/assets/d8884ac0-fc7e-48e7-b528-387e5d01e5e0)

2024-08-09 05:54 UTC, hasali19 commented
Please can you share your flutter and android versions, device information, debug logs and a link to a code repo if possible.

2024-08-09 06:37 UTC, wildsylvan commented
thanks for the quick reply! here:

`flutter doctor`
```
[√] Flutter (Channel beta, 3.24.0-0.2.pre, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.1)
[√] Connected device (3 available)
[√] Network resources
```

testing on a real phone, `oneplus 8t` with `android 14`
![image](https://github.com/user-attachments/assets/f1199c4e-9352-47d8-ac1c-fc0ecee1f234)

---

i can provide a repro next week... it's very vanilla use of material components tho, not many customizations

2024-08-09 06:39 UTC, wildsylvan commented
this is the oneplus color settings:
![image](https://github.com/user-attachments/assets/7d3ce754-f7bf-4042-beb5-cbcddb7906e9)

2024-08-09 06:45 UTC, wildsylvan commented
ok these impact how colors are shown in the app:
![image](https://github.com/user-attachments/assets/30126bbf-a443-4057-a12b-e7cc9966fa91)

but the difference between primary container e secondary container remains basically non-existent

2024-08-09 06:48 UTC, wildsylvan commented
@hasali19 what would be the best way to ignore completely oneplus color presets, just get the "main accent color" from android and utilize that color to build a correct material 3 color palette?

2024-08-09 07:10 UTC, hasali19 commented
Thanks for the info. Given that you are using Android 14 where the colours are retrieved directly from the system without any conversion, it is likely OnePlus is simply reporting both colours as the same.

One thing you could try is to force use of the fallback method used for older versions of Android, e.g:
```dart
final corePalette = await DynamicColorPlugin.getCorePalette();
final lightDynamic = corePalette?.toColorScheme(brightness: Brightness.light);
final darkDynamic = corePalette?.toColorScheme(brightness: Brightness.dark);
```

If you just want a specific "accent" colour, you can pick one from the fields on the colour schemes provided by `DynamicColorBuilder`.

2024-08-10 10:55 UTC, wildsylvan commented
_update_

---

```dart
final corePalette = await DynamicColorPlugin.getCorePalette();
final lightDynamic = corePalette?.toColorScheme(brightness: Brightness.light);
final darkDynamic = corePalette?.toColorScheme(brightness: Brightness.dark);
```
doesn't fix the issue

---

my colleague tested with his Pixel 7 Pro (and also inside an emulator) and he has the same issue

the issue seems to be present **only in light mode** tho (and our theme settings don't have any specific setting for either of them):

# wrong in light mode
![image](https://github.com/user-attachments/assets/5efac110-e2b7-4685-9b80-0b2867f16c44)

# correct in dark mode
![image](https://github.com/user-attachments/assets/15f31ae5-83c4-49c0-8475-a817eb4301c1)

2024-08-10 11:00 UTC, wildsylvan commented
this is the card (the one with the text Test):
![image](https://github.com/user-attachments/assets/83bf6a57-dfa3-4eff-9755-25a1070a5774)

and this is the fab:
![image](https://github.com/user-attachments/assets/39b27883-4971-4693-b29e-e82b7e0f14a2)

2024-08-10 11:22 UTC, hasali19 commented
Although it's subtle, the colours in your screenshot do appear to be slightly different. I'm also able to reproduce very similar looking colours in light mode when running in an emulator.

![image](https://github.com/user-attachments/assets/a5dafa2c-5a86-4efe-aa04-195571b6d628)

2024-08-10 11:23 UTC, wildsylvan commented
yeah i was just about to write it! they are a little different... so it's an more general issue with the way the m3 color generator work?

2024-08-10 11:25 UTC, wildsylvan commented
with a green wallpaper the difference is less subtle too...

![image](https://github.com/user-attachments/assets/5ed26be6-e414-4906-8921-efd801cfdf91)

2024-08-10 11:26 UTC, hasali19 commented
Right, I guess it's just an artifact of whatever algorithm Android uses to pick the system colours.

2024-08-10 11:32 UTC, wildsylvan commented
well to be fair the material theme builder shows it too with the blues (tho they difference is a little more visible):
![image](https://github.com/user-attachments/assets/8e72039c-8e3a-4755-9adf-fed1849e7f61)

while the green is much less subtle:
![image](https://github.com/user-attachments/assets/dca2a8a8-d261-40db-b3b3-b9329cb22d8c)

@guidezpl is it supposed to be that different between hues?

2024-11-26 11:40 UTC, im-trisha commented
It seems like the card color is incorrect... Is it just me or...?

Not just the card color, but also the bottom nav bar and many other colors seem to be washed off (see, the one on the left is way more purple)

![image](https://github.com/user-attachments/assets/7e86b55e-043a-4b74-83f1-6bd57d5fbfee)

2025-01-01 13:04 UTC, hasali19 commented
Given that nobody appears to be maintaining this repo, I have published my fork to pub.dev as [dynamic_system_colors](https://pub.dev/packages/dynamic_system_colors).

2025-08-01 10:34 UTC, guidezpl commented
Hi, this repo is maintained sporadically when I have time, but also it is summer and I am on vacation :) please be patient and I will review when back

2025-09-02 12:45 UTC, guidezpl requested changes

2025-09-02 12:45 UTC, guidezpl commented on packages/dynamic_color/lib/src/corepalette_to_colorscheme.dart
> +    primary: Color(corePalette.primary.get(40)),
Unfortunately, these values only work for one type of scheme, there are many types. See https://github.com/material-foundation/material-color-utilities/blob/main/dev_guide/creating_color_scheme.md

2025-09-02 12:45 UTC, guidezpl commented on packages/dynamic_color/lib/src/corepalette_to_colorscheme.dart
> +// Once flutter updates to the latest version, this workaround can be removed.
Best to wait for https://github.com/flutter/flutter/pull/170000 rather than introduce workarounds IMO

2025-09-02 12:45 UTC, guidezpl commented on packages/dynamic_color/lib/src/color_schemes.dart
> +
This is somewhat fragile an difficult to validate correctness with DynamicColorPlugin.kt

2025-09-02 12:45 UTC, guidezpl commented on packages/dynamic_color/android/src/main/kotlin/io/material/plugins/dynamic_color/DynamicColorPlugin.kt
> +      // light
Why not obtain `system_palette_key_color_primary_light` and other key colors and generate the scheme directly?

2025-09-02 12:48 UTC, guidezpl commented
To anyone on this PR with issues, please create a new separate issue if appropriate, or refer to an existing one, it's really hard to follow the discussion here

2025-09-07 08:20 UTC, hasali19 commented on packages/dynamic_color/lib/src/corepalette_to_colorscheme.dart
> +    primary: Color(corePalette.primary.get(40)),
I've read through that page and I confess I'm not entirely sure what you mean. The point of this code is to generate a _specific_ colour scheme based on the system colour palette. The values used here are taken from the official Android material library - https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md. The dynamic colour implementation in Jetpack Compose is also [implemented](https://github.com/androidx/androidx/blob/androidx-main/compose/material3/material3/src/androidMain/kotlin/androidx/compose/material3/DynamicTonalPalette.android.kt#L262-L305) in a similar way.

2025-09-07 08:25 UTC, hasali19 commented on packages/dynamic_color/android/src/main/kotlin/io/material/plugins/dynamic_color/DynamicColorPlugin.kt
> +      // light
Is that guaranteed to return the same colours as this code that is querying from the system? Again, this code is based on the official Android implementation [here](https://github.com/androidx/androidx/blob/androidx-main/compose/material3/material3/src/androidMain/kotlin/androidx/compose/material3/DynamicTonalPalette.android.kt#L311-L409), and I think it would be good to keep the implementation as similar as possible to ensure consistency with non-Flutter apps.

2025-09-07 08:28 UTC, hasali19 commented on packages/dynamic_color/lib/src/color_schemes.dart
> +
Good point, I'll see if I can improve that. Perhaps a map with readable names instead of a list?

2025-09-07 08:32 UTC, hasali19 commented
Thanks for the review @guidezpl! I've responded to your comments - main theme is that I've tried to keep the implementation close to what the official Android dynamic colour implementation does, to ensure consistency with non-flutter apps.

2026-08-07 09:36 UTC, guidezpl commented
With recent changes and 1.9.0 out, I'm going to close this. Thanks!

2026-08-07 09:36 UTC, closed without merging